%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/michaelsanne/Documents/UCT/4th Year/Theses/Matlab/MonocularVisualOdometry/Data/1LoopDown/vicon_1loopDown.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/10/12 11:36:22

%% Initialize variables.
filename = 'Data/1LoopDown/vicon_1loopDown_Image_copy.txt';
startRow = 4;

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%17f%11f%11f%11f%11f%11f%11f%11f%11f%11f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow-1, 'WhiteSpace', '', 'ReturnOnError', false, 'EndOfLine', '\r\n');
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'EmptyValue' ,NaN,'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
vicon1loopDown = table(dataArray{1:end-1}, 'VariableNames', {'Timestamp','x','y','z','roll','pitch','yaw','xAngularRate','yAngularRate','zAngularRate'});
groundTruthPoses = table();

count = 0;
for i = 1:height(vicon1loopDown)
    count = count+1;
    vicon.ViewId = count;
    vicon.Location = {table2array(vicon1loopDown(i,2:4))};
    if (i == 1) 
        Loc = vicon.Location{1};
    end
    vicon.Location{1} = vicon.Location{1} - Loc;
    
    roll = table2array(vicon1loopDown(i,5));
    pitch = table2array(vicon1loopDown(i,6));
    yaw = table2array(vicon1loopDown(i,7));
    dcm = angle2dcm( yaw, pitch, roll);
    vicon.Orientation = {dcm};
    Rotation = eye(3);
    if (i == 1) 
        Rotation = vicon.Orientation{1}';
    end
    
    %vicon.Orientation = vicon.Orientation.*Rotation;
    vicon.Orientation{1} = vicon.Orientation{1}*Rotation;
    
    groundTruthPoses(count,:) = struct2table(vicon);
end    

%% Clear temporary variables
clearvars filename startRow formatSpec fileID dataArray ans;
